### PR TITLE
Remove `encoding` option

### LINKED ISSUE #67: Issues with the `encoding` option
The `encoding` option has the following issues.

### 1. It does not work with `getStreamAsBuffer()`

The `encoding` option is currently limited to `getStream()`. It is a noop when using `getStreamAsBuffer()`. 

https://github.com/sindresorhus/get-stream/blob/c96088793daae528337d1f15b52a3e8b4ce2d9dd/index.js#L51-L53

### 2. It handles the output encoding, not the input one

While the `encoding` option is [currently documented](https://github.com/sindresorhus/get-stream#encoding) as `The encoding of the incoming stream.`, it is actually the encoding of the output instead. For example, it cannot be used to decode an incoming hex/base64/etc. stream. Instead, it encodes the incoming stream.

```js
import {compose} from 'node:stream'
import getStream from 'get-stream'

console.log(await getStream(compose([Buffer.from('...').toString('hex')]))) // 2e2e2e, as expected
console.log(await getStream(compose([Buffer.from('...').toString('hex')]), {encoding: 'hex'})) // 326532653265, not ...
```

### 3. It is not needed for buffer/string difference

Using buffer vs string as input or output is handled without the need of the `encoding` option. Especially now that a separate method exists for buffers.

### 4. Encoding is a separate concern

Based on the above, the `encoding` option's only purpose is the following: encoding the return value as a hex or base64 string. It can also be used for 	`latin1`, etc., but returning those less common encodings as output seems much less useful.

However, encoding a string as hex or base64 can be done fairly simply and in many different ways, outside of this package. Encoding as hex without streaming can be as simple as `(await getStreamAsBuffer(stream)).toString('hex')`. Base64 streaming can be done with packages like [`b64`]*https://github.com/hapijs/b64), and without streaming with `.toString('base64')` or `btoa()`.

In general, it seems like one would want to use `get-stream` to consume a stream in an easy and safe fashion, but encoding it to hex or base64 might be a separate concern better handled by other packages.

### 5. Its implementation might lead to bugs

The current implementation requires using a `PassThrough` stream instead of consuming the input stream directly. This additional layer has created issues such as #52, because the `PassThrough` stream does its own buffering.

### 6. It is slower

The intermediate stream requires its own computation, i.e. it is slower (although probably not much). It might also lead to [inefficient buffering strategies](https://github.com/sindresorhus/get-stream/pull/66#discussion_r1286176762).

### 7. This prevents supporting `ReadableStream`

The current implementation could easily support web-compatible `ReadableStream`, in addition to Node.js-specific streams, since it simply iterates with `for await`, which works well with `ReadableStream`. However, the `encoding` option would be difficult to support with `ReadableStream`. `TextDecoder` does not work since the `encoding` option encodes (not decodes). `TextEncoder` does not work because can only encodes to `utf8`. Also the list of encodings supporting in the browsers are different from the ones supported by Node.js.

---

Based on the above, I am curious whether you'd consider removing the `encoding` option @sindresorhus? Besides making the code simpler, faster and more resilient, it would enable supporting `ReadableStream`. I'd be happy to implement both of this, if you think this is a good idea.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #67.

This removes the `encoding` option. 

This is a breaking change for users who used the `encoding` option with `getStream()` (not with `getStreamAsBuffer()`) except if they used `encoding: undefined`, `encoding: null` or `encoding: 'utf8`. For users who used `encoding: 'hex'`, please convert to hexadecimal using `Buffer.from(string).toString('hex')`. For those who used `encoding: 'base64'`, please convert to base64 using either `Buffer.from(string).toString('base64')` or (for better performance on big streams) with [`b64`](https://github.com/hapijs/b64).

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -9,45 +8,54 @@ export class MaxBufferError extends Error {
...
+const getContentsAsBuffer = (chunks, length) => Buffer.concat(chunks, length);
+
+const convertChunkToString = chunk => typeof chunk === 'string' ? chunk : chunk.toString();
+
+const getContentsAsString = chunks => chunks.join('');
+
+const chunkTypes = {
+	buffer: {convertChunk: convertChunkToBuffer, getContents: getContentsAsBuffer},
+	string: {convertChunk: convertChunkToString, getContents: getContentsAsString},
+};
```
Comment (ehmicky) [inline index.js:61]: This allows adding more types, such as `ArrayBuffer`, which would be helpful to support `ReadableStream`.
